from enum import Enum
from typing import List, Optional, TYPE_CHECKING
from datetime import datetime

from sqlalchemy import (
    String, Integer, ForeignKey, Text, Enum as SqlEnum,
    DateTime, Boolean
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from Models import Base # Assuming Base is defined in Models/__init__.py or similar

if TYPE_CHECKING:
    from .user_models import User, Stakeholder
    from .department_models import Department

# ========================
# Institute Model
# ========================

class Institute(Base):
    __tablename__ = "institutes"

    # This is already configured to be auto-generated by the database.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    address: Mapped[Optional[str]] = mapped_column(String(255))
    contact_email: Mapped[Optional[str]] = mapped_column(String(255))
    contact_phone: Mapped[Optional[str]] = mapped_column(String(20))
    is_approved: Mapped[bool] = mapped_column(Boolean, default=False)
    
    # IMPROVEMENT: Using server_default ensures the database sets the timestamp.
    # This makes it optional for you to provide when creating an institute.
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now())

    # These relationships are already optional. They will be empty lists by default.
    departments: Mapped[List["Department"]] = relationship(back_populates="institute")
    users: Mapped[List["User"]] = relationship(back_populates="institute")
    stakeholders: Mapped[List["Stakeholder"]] = relationship(back_populates="institute")

    def __repr__(self):
        created_str = self.created_at.isoformat() if self.created_at else None
        return (f"Institute(id={self.id}, name='{self.name}', code='{self.code}', "
                f"is_approved={self.is_approved}, created_at='{created_str}')")